# CodeRabbit Configuration
# Docs: https://docs.coderabbit.ai/reference/configuration

language: en-US
tone_instructions: 'Be concise and actionable. Focus on bugs, security issues, and significant improvements.'
early_access: false

reviews:
  profile: chill # Options: chill, assertive
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggest_labels: true
  auto_apply_labels: false
  request_changes_workflow: false

  # Path-specific instructions
  path_instructions:
    - path: '**/*.py'
      instructions: 'Check for type hints, proper exception handling, and PEP 8 compliance.'
    - path: '**/*.ts'
      instructions: "Ensure proper TypeScript types, avoid 'any', and check for null safety."
    - path: '**/*.tsx'
      instructions: 'Review React hooks usage, component structure, and accessibility.'
    - path: '**/tests/**'
      instructions: 'Verify test coverage, meaningful assertions, and edge cases.'

  # Files to ignore
  path_filters:
    - '!**/node_modules/**'
    - '!**/dist/**'
    - '!**/build/**'
    - '!**/*.min.js'
    - '!**/package-lock.json'
    - '!**/yarn.lock'
    - '!**/.next/**'
    - '!**/coverage/**'

  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords:
      - 'WIP'
      - 'DO NOT MERGE'
      - '[skip ci]'
    base_branches: []

  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

  # Pre-merge checks
  pre_merge_checks:
    title_check:
      mode: warning
    description_check:
      mode: warning
    linked_issue_assessment:
      mode: warning

# Static analysis tools
tools:
  # JavaScript/TypeScript
  eslint:
    enabled: true
  biome:
    enabled: true

  # Python
  ruff:
    enabled: true
  flake8:
    enabled: true
  pylint:
    enabled: true

  # Security
  gitleaks:
    enabled: true
  semgrep:
    enabled: true

  # General
  shellcheck:
    enabled: true
  markdownlint:
    enabled: true
  yamllint:
    enabled: true
  actionlint:
    enabled: true
  hadolint:
    enabled: true

  # Disabled tools (enable as needed)
  phpstan:
    enabled: false
  rubocop:
    enabled: false
  golangci-lint:
    enabled: false
  swiftlint:
    enabled: false

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  learnings:
    scope: auto
  issues:
    scope: auto
  pull_requests:
    scope: auto
  code_guidelines:
    enabled: true

code_generation:
  docstrings:
    language: en-US
  unit_tests:
    path_instructions:
      - path: '**/*.py'
        instructions: 'Use pytest with fixtures. Follow AAA pattern (Arrange, Act, Assert).'
      - path: '**/*.ts'
        instructions: 'Use Jest or Vitest. Mock external dependencies.'
